sudo: required
services:
  - docker

before_install:
  - docker build -t aurelius88/docker -f Dockerfile.dev .

script:
  - docker run aurelius88/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-556005707383"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure:  "$AWS_SECRET_KEY"